/**
 * Stability AI service implementation
 * Requires API key for all operations
 */

import StabilityAI from 'stability-ai';
import { readFile, unlink } from 'node:fs/promises';
import type { AIServiceAdapter, GenerationResult } from './types.js';
import { AIServiceError } from '../errors.js';

/**
 * StabilityService implements AIServiceAdapter for Stability AI
 * Paid service requiring API key
 */
export class StabilityService implements AIServiceAdapter {
  private client: StabilityAI;

  /**
   * Create Stability service
   * @param apiKey Stability AI API key (required)
   */
  constructor(apiKey: string) {
    this.client = new StabilityAI(apiKey);
  }

  getServiceName(): string {
    return 'Stability';
  }

  requiresApiKey(): boolean {
    // Stability AI requires API key
    return true;
  }

  getTimeout(): number {
    // 90 seconds - slower than OpenAI, free tier can be slow
    return 90000;
  }

  async generateImage(prompt: string): Promise<GenerationResult> {
    try {
      // Use Stable Diffusion XL model
      const results = await this.client.v1.generation.textToImage(
        'stable-diffusion-xl-1024-v1-0',
        [{ text: prompt, weight: 1.0 }]
      );

      if (!results || results.length === 0) {
        throw new Error('No images generated by Stability AI');
      }

      const result = results[0];

      // SDK saves to filesystem - read buffer from filepath
      const buffer = await readFile(result.filepath);

      // CRITICAL: Clean up SDK's temp file immediately after reading
      // Defensive against SDK file leaks that can accumulate over time
      await unlink(result.filepath).catch(() => {
        // Suppress cleanup errors (file might be in temp dir that OS cleans)
      });

      return {
        buffer,
        contentType: 'image/png',
        service: 'Stability'
      };
    } catch (error: any) {
      // Translate API errors to user-friendly messages
      const errorMessage = error?.message || String(error);
      const statusCode = error?.response?.status;

      // 401: Invalid API key
      if (statusCode === 401 || errorMessage.toLowerCase().includes('unauthorized')) {
        throw new AIServiceError(
          'Stability',
          errorMessage,
          'Invalid Stability AI API key. Get your API key from https://platform.stability.ai/account/keys'
        );
      }

      // 429: Rate limit exceeded
      if (statusCode === 429 || errorMessage.toLowerCase().includes('rate limit')) {
        throw new AIServiceError(
          'Stability',
          errorMessage,
          'Rate limit exceeded. Wait a few moments or upgrade your Stability AI plan.'
        );
      }

      // 400: Content policy or invalid parameters
      if (statusCode === 400 || errorMessage.includes('400')) {
        throw new AIServiceError(
          'Stability',
          errorMessage,
          'Your prompt may violate content policy or contain invalid parameters. Try simplifying your prompt.'
        );
      }

      // Generic error
      throw new AIServiceError(
        'Stability',
        errorMessage,
        `Failed to generate image with Stability AI: ${errorMessage}`
      );
    }
  }
}
